version: "3.7"

services:
  dollar:
    depends_on:
      - postgresdb
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./data/dollar:/app/data
    env_file:
      - ./.env

  postgresdb:
    image: postgres:15-alpine
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - ./.env
